### ISSUE TITLE
No server support

### ISSUE THREAD

**Issue by xannor** [JackyyTV/ActuallyBaubles#1]
Dedicated server launch with 1.11.2-1.1 crashes with

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Actually Baubles (actuallybaubles)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
        at me.jacky1356400.actuallybaubles.ActuallyBaubles.init(ActuallyBaubles.java:47)

**Comment by JackyyTV** [comment]
Some client codes tried to run on the server, which I was not aware about. Will push a fix later today.

**Comment by JackyyTV** [comment]
I have no idea why the commit didn't close the issue, but [issue is fixed on 1.1.1](https://github.com/Jacky1356400/ActuallyBaubles/releases/tag/1.11.2-1.1.1)
I'll push that update onto CurseForge in a bit.
