### ISSUE TITLE
Ring of magnetizing

### ISSUE THREAD

**Issue by totte1015** [JackyyTV/ActuallyBaubles#3]
So I currently have a non-hand-only ring in my inventory, the magnetizing from AA...

I press the ringbutton next to the player in inventory screen and try to put that ring in any of the ring icons, but none works...

What am I doing wrong?

**Comment by JackyyTV** [comment]
Have you put the ring into the crafting grid to get the bauble version first?

**Comment by totte1015** [comment]
Oh wow thanks stupid brain for fast reading through the description! 😆 

I totally skipped the 2nd line of it... Thanks!
